/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kbs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List knowledge bases */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description KB list for the authenticated tenant */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Per-tenant daily API request quota exceeded (UTC day; see SETTINGS#tenant overrides) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailyQuotaExceeded"];
                    };
                };
            };
        };
        put?: never;
        /** Create knowledge base */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseCreate"];
                };
            };
            responses: {
                /** @description KB created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Per-tenant daily API request quota exceeded (UTC day) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailyQuotaExceeded"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kbs/{kbId}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** RAG query — dense retrieval + bounded context + Bedrock generation (+ audit) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RagQueryRequest"];
                };
            };
            responses: {
                /** @description Model answer plus chunk citations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RagQueryResponse"];
                    };
                };
                /** @description Invalid JSON, non-object body, or JSON Schema validation failure before Bedrock */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestInvalidJson"] | components["schemas"]["BadRequestSchemaValidation"];
                    };
                };
                /** @description KB not visible to tenant */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Per-tenant daily API request quota exceeded (UTC day) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailyQuotaExceeded"];
                    };
                };
                /** @description OpenSearch/search transport error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Live search unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kbs/{kbId}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dense vector search / optional hybrid BM25+kNN (SEARCH_MODE=stub|live OpenSearch) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DenseSearchRequest"];
                };
            };
            responses: {
                /** @description Ranked chunks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DenseSearchResponse"];
                    };
                };
                /** @description Invalid JSON, non-object body, JSON Schema validation failure, or live search rules (e.g. missing query_embedding; hybrid without q/embedding; both weights 0)
                 *      */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BadRequestInvalidJson"] | components["schemas"]["BadRequestSchemaValidation"] | {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Per-tenant daily API request quota exceeded (UTC day) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailyQuotaExceeded"];
                    };
                };
                /** @description OpenSearch error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Live search but OpenSearch not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kbs/{kbId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presigned PUT for raw document */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kbs/{kbId}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start ingest job (Step Functions) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Object key returned from uploads */
                        s3_key?: string;
                        embedding_model_id?: string;
                        chunk_chars?: number;
                    };
                };
            };
            responses: {
                /** @description Job accepted (QUEUED); poll GET job until terminal state */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestJobCreated"];
                    };
                };
                /** @description Pipeline not configured */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kbs/{kbId}/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll job status (primary; PK=`KB#{kbId}`, SK=`JOB#{jobId}`) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kbId: string;
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current job snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobPollResponse"];
                    };
                };
                /** @description Job not visible to tenant */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Job missing */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll job status (O(1) with `kb_id` query; otherwise GSI tenant+job lookup) */
        get: {
            parameters: {
                query?: {
                    /** @description When set, load by base-table PK/SK `KB#kb_id` + `JOB#jobId` (recommended) */
                    kb_id?: string;
                };
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current job snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobPollResponse"];
                    };
                };
                /** @description Job missing */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plugins/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register plugin manifest */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Malformed JSON or a JSON document that is not an object (400) */
        BadRequestInvalidJson: {
            /** @example Bad Request */
            title: string;
            detail: string;
        };
        BadRequestSchemaValidation: {
            /** @example Bad Request */
            title: string;
            /** @example Request body failed JSON Schema validation */
            detail: string;
            schema_errors: {
                message: string;
            }[];
        };
        /** @description Returned before route logic when the tenant's UTC-day counter (Dynamo ``QUOTA#YYYY-MM-DD``) would exceed the limit. Disable per tenant with ``quota_exempt`` on ``SETTINGS#tenant``, or raise/lower cap with ``requests_per_day_limit`` (N). Lambda env ``TENANT_REQUESTS_PER_DAY`` (``0`` disables quotas globally).
         *      */
        DailyQuotaExceeded: {
            /** @example Too Many Requests */
            title: string;
            detail: string;
            /** @description UTC calendar date for the quota bucket (YYYY-MM-DD) */
            quota_date: string;
            limit: number;
        };
        KnowledgeBaseCreate: {
            name?: string;
            /** @description Default embedding model stored on the KB record */
            embedding_model_id?: string;
            /** @description Optional default Bedrock guardrail identifier for `/v1/kbs/{kbId}/query` when the request does not specify guardrail fields (`guardrails_*` / `guardrailIdentifier`)
             *      */
            bedrock_guardrail_id?: string;
            /** @description Guardrail version; stored when `bedrock_guardrail_id` is set */
            bedrock_guardrail_version?: string;
            /** @description Alias for `bedrock_guardrail_id` */
            guardrailIdentifier?: string;
            /** @description Alias for `bedrock_guardrail_version` */
            guardrailVersion?: string;
        };
        JobStatus: components["schemas"]["job-status.schema"];
        /** @description Single chunk hit from OpenSearch `_source` */
        DenseSearchHit: {
            /** @description Document `_id` */
            id: string;
            /** @description kNN relevance score (`_score`) */
            score: number;
            /** @description chunk_text field (OpenSearch document column) */
            text: string;
            /** @description Optional metadata map stored with the chunk */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        DenseSearchRequest: {
            /**
             * @description When true in live mode, run hybrid search — lexical `multi_match` on `chunk_text` plus kNN on `embedding` in a single `bool` query (`should`), with boosts from `bm25_weight` / `vector_weight`. Requires non-empty `q` and `query_embedding`.
             * @default false
             */
            hybrid: boolean;
            /**
             * @description Boost on the lexical `multi_match` branch (ignored unless `hybrid=true`)
             * @default 1
             */
            bm25_weight: number;
            /**
             * @description Boost on the kNN embedding branch (ignored unless `hybrid=true`; cannot both weights be 0 when hybrid)
             * @default 1
             */
            vector_weight: number;
            /** @description Free-text query (stub mode); required non-empty when `hybrid=true` in live mode */
            q?: string;
            /** @description Query vector (`SEARCH_MODE=live` vector search requires this; hybrid also requires this) */
            query_embedding?: number[];
            /**
             * @description kNN neighbor count (`top_k` alias)
             * @default 5
             */
            k: number;
            /** @description Alias for `k` */
            top_k?: number;
            /** @description Passed to OpenSearch `min_score` (optional) */
            min_score?: number;
        };
        DenseSearchResponse: {
            kb_id: string;
            hits: components["schemas"]["DenseSearchHit"][];
            total: number;
            /** @description e.g. `opensearch-serverless-stub`, `opensearch-serverless-knn`, or `opensearch-serverless-hybrid` when `hybrid=true` */
            backend: string;
            /** @description Present and true when hits were reordered by the optional rerank Lambda or `RERANK_URL` hook (up to 20 candidates, response truncated to requested `k`) */
            reranked?: boolean;
        };
        /** @description Retrieval uses `CONTEXT_CHAR_BUDGET` (default 12000) for joined chunk text cap. Generation uses Lambda env `GENERATION_MODEL_ID`, `MAX_TOKENS`, `TEMPERATURE`; optional `QUERY_USE_CONVERSE_STREAM=true` aggregates ConverseStream to a single reply. Audit rows use `PK=TENANT#…`, `SK=QUERYAUDIT#<UTC-ISO-ms>#<uuid>` (and sparse GSI `GSIQueryAuditTime` on `GSI2PK=TENANT#…#QUERYAUDIT`, `GSI2SK=<ISO>#<uuid>` for time-range queries). Persisted fields include `question_sha256`, `answer_length`, `model_id`, `latency_ms`, `hit_ids`, `prompt_sha256`, `audit_stub_next` (QUERY_AUDIT_EXTENSION_STUB), optional guardrail keys, and optional `expires_at` (Unix epoch) when Lambda env `QUERY_AUDIT_TTL_DAYS` is a positive integer (table TTL enabled on `expires_at`).
         *      */
        RagQueryRequest: components["schemas"]["DenseSearchRequest"] & {
            /** @description User question (also used as lexical `q` fallback when `q` is omitted) */
            question: string;
            /**
             * @description How many top ranked hits to concatenate into the generator context (after optional rerank).
             *     Default can be overridden via Lambda env `CONTEXT_K_DEFAULT`.
             *
             * @default 8
             */
            context_k: number;
            /** @description Overrides control-plane Lambda env GENERATION_MODEL_ID when set (Claude, Titan Text, and other foundation models exposed for Converse / ConverseStream). */
            model_id?: string;
            /** @description Optional Bedrock guardrail id (highest precedence in the request body) */
            guardrails_id?: string;
            /** @default DRAFT */
            guardrails_version: string;
            /** @description Alias for guardrails_id (Bedrock/API naming) */
            guardrailIdentifier?: string;
            /** @description Alias for guardrails_version */
            guardrailVersion?: string;
        };
        RagQueryResponse: {
            answer: string;
            citations: {
                /** @description Dense hit / chunk id surfaced to the user */
                id: string;
            }[];
            kb_id: string;
            guardrails_applied: boolean;
        };
        /** @description Mirrors DynamoDB ingest job projection (stable keys for UI polling) */
        JobPollResponse: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["job-status.schema"];
            kb_id: string | null;
            /** @description S3 manifest key when worker finished first pass */
            manifest_key: string | null;
            /** @description Set after ingest completes (`null` while RUNNING early) */
            chunk_count: number | null;
            /** @description Embedding model id (persisted from job POST / worker SFN payload) */
            embed_model: string | null;
            bulk_indexed: number;
            bulk_failed: number;
            /** @description OpenSearch bulk failure document `_id`s (subset may be persisted) */
            errors: string[];
        };
        IngestJobCreated: {
            id: string;
            /**
             * @description Initial status when POST returns 202 (`JobStatus`; see schema)
             * @enum {string}
             */
            status: "QUEUED";
            s3_key?: string;
        };
        /**
         * JobStatus
         * @description DynamoDB job item lifecycle for ingest pipeline (backward compatible with existing QUEUED/SUCCEEDED rows).
         * @enum {string}
         */
        "job-status.schema": "QUEUED" | "RUNNING" | "SUCCEEDED" | "PARTIAL" | "FAILED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
